import type { Metadata } from "next";
import Link from 'next/link';
import "./globals.css";
import AuthNav from "./_components/AuthNav";

export const metadata: Metadata = {
  title: "Secure Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning={true}>
      <body>
        <div className="min-h-screen bg-gray-100">
          <nav className="bg-white shadow p-4 flex justify-between items-center">
            <Link href="/" className="text-lg font-bold">
              Secure Web App
            </Link>
            <AuthNav />
          </nav>

          <main className="p-6">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}

